
/*
 * Keeps track of various constants throughout the app
 */

angular.module('app.Values', [])
.value('categories', [
  'Animation',
  'Branding',
  'Casting',
  'Color Correcting',
  'Database Development',
  'Directorial',
  'Duplication/Distribution',
  'Editorial',
  'Event Management',
  'Experiential',
  'Illustrators/Artists',
  'Mobile Development',
  'Motion Graphics/Design',
  'Music',
  'Online Banner Development',
  'Photography',
  'Post Production',
  'Print',
  'Production',
  'Promo/Specialty',
  'Research',
  'Sound',
  'Translations',
  'Visual Effects',
  'Web Development'
])
.value('classifications', [
  'DBE',
  'EDWOSB',
  'HUB',
  'MBE',
  'SBA 8(a)',
  'SBE',
  'SDB',
  'WBE',
  'WOSB'
])
.value('states', [
  {"state": "AL"},
  {"state": "AK"},
  {"state": "AS"},
  {"state": "AZ"},
  {"state": "AR"},
  {"state": "CA"},
  {"state": "CO"},
  {"state": "CT"},
  {"state": "DE"},
  {"state": "DC"},
  {"state": "FM"},
  {"state": "FL"},
  {"state": "GA"},
  {"state": "GU"},
  {"state": "HI"},
  {"state": "ID"},
  {"state": "IL"},
  {"state": "IN"},
  {"state": "IA"},
  {"state": "KS"},
  {"state": "KY"},
  {"state": "LA"},
  {"state": "ME"},
  {"state": "MH"},
  {"state": "MD"},
  {"state": "MA"},
  {"state": "MI"},
  {"state": "MN"},
  {"state": "MS"},
  {"state": "MO"},
  {"state": "MT"},
  {"state": "NE"},
  {"state": "NV"},
  {"state": "NH"},
  {"state": "NJ"},
  {"state": "NM"},
  {"state": "NY"},
  {"state": "NC"},
  {"state": "ND"},
  {"state": "MP"},
  {"state": "OH"},
  {"state": "OK"},
  {"state": "OR"},
  {"state": "PW"},
  {"state": "PA"},
  {"state": "PR"},
  {"state": "RI"},
  {"state": "SC"},
  {"state": "SD"},
  {"state": "TN"},
  {"state": "TX"},
  {"state": "UT"},
  {"state": "VT"},
  {"state": "VI"},
  {"state": "VA"},
  {"state": "WA"},
  {"state": "WV"},
  {"state": "WI"},
  {"state": "WY"}
]);

