
/*
 * Keeps track of various constants throughout the app
 */

angular.module('app.Values', [
  'site.constants'
])
.value('classifications', [
  'DBE',
  'EDWOSB',
  'HUB',
  'MBE',
  'SBA 8(a)',
  'SBE',
  'SDB',
  'WBE',
  'WOSB'
])
.value('states', [
  {"state": "AL"},
  {"state": "AK"},
  {"state": "AS"},
  {"state": "AZ"},
  {"state": "AR"},
  {"state": "CA"},
  {"state": "CO"},
  {"state": "CT"},
  {"state": "DE"},
  {"state": "DC"},
  {"state": "FM"},
  {"state": "FL"},
  {"state": "GA"},
  {"state": "GU"},
  {"state": "HI"},
  {"state": "ID"},
  {"state": "IL"},
  {"state": "IN"},
  {"state": "IA"},
  {"state": "KS"},
  {"state": "KY"},
  {"state": "LA"},
  {"state": "ME"},
  {"state": "MH"},
  {"state": "MD"},
  {"state": "MA"},
  {"state": "MI"},
  {"state": "MN"},
  {"state": "MS"},
  {"state": "MO"},
  {"state": "MT"},
  {"state": "NE"},
  {"state": "NV"},
  {"state": "NH"},
  {"state": "NJ"},
  {"state": "NM"},
  {"state": "NY"},
  {"state": "NC"},
  {"state": "ND"},
  {"state": "MP"},
  {"state": "OH"},
  {"state": "OK"},
  {"state": "OR"},
  {"state": "PW"},
  {"state": "PA"},
  {"state": "PR"},
  {"state": "RI"},
  {"state": "SC"},
  {"state": "SD"},
  {"state": "TN"},
  {"state": "TX"},
  {"state": "UT"},
  {"state": "VT"},
  {"state": "VI"},
  {"state": "VA"},
  {"state": "WA"},
  {"state": "WV"},
  {"state": "WI"},
  {"state": "WY"}
]);

